### ISSUE TITLE
Login with token issue

### ISSUE THREAD

**Issue by Lazarica-t** [ridleyco/DynaHub#3]
Hi,

The automatic login with a GitHub token does not seem to work.
I've created a generic credential and named it DynaHub but when I open Dynamo and pick login with token nothing happens, I have to manually input the GitHub token to be able to log in.

![image](https://user-images.githubusercontent.com/49474519/84126257-580e8280-aa46-11ea-9dba-6b66c045fb78.png)
![image](https://user-images.githubusercontent.com/49474519/84126318-6c527f80-aa46-11ea-93bb-e994bfdf3923.png)
![image](https://user-images.githubusercontent.com/49474519/84126380-7ffde600-aa46-11ea-89b2-44d75fc120d8.png)

Kind Regards

**Comment by Dre-Tas** [comment]
Hi Lazarica

Thanks for reaching out. I'm happy to see you're using DynaHub and that you created the first Issue for the project!

The Credentials side looks right. Are you using the latest version of DynaHub (2.5.2)?
Earlier version of DynaHub (< 2.5.0 if I'm not mistaken) don't implement the credentials management.

**Comment by Lazarica-t** [comment]
Yes, I am using the 2.5.2 version. 
Can it have something to do with the Windows version? 

![image](https://user-images.githubusercontent.com/49474519/84144629-3e2e6900-aa61-11ea-8379-136947c2cfd9.png)

Kind Regards

**Comment by Dre-Tas** [comment]
What does it way under the token text box?
![image](https://user-images.githubusercontent.com/36023527/84215000-61602380-ab08-11ea-8962-587b807dd934.png)

**Comment by Lazarica-t** [comment]
This is what I get:
![image](https://user-images.githubusercontent.com/49474519/84237479-1a6f2f80-ab02-11ea-93fe-16fd343ef15d.png)

**Comment by Dre-Tas** [comment]
@Lazarica-t thanks for spotting that bug! I should have fixed it now in version 2.5.3
Please install the new version and let me know if it works now

**Comment by Lazarica-t** [comment]
Works like a charm!
Thanks! You're awesome!
![image](https://user-images.githubusercontent.com/49474519/84253332-7c3a9400-ab18-11ea-97ee-478097932577.png)
